#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Generate the runtime wiring maps under docs/ai/.

Seata wires most of its extension points at runtime: SPI implementations are
picked by name through EnhancedServiceLoader, RPC messages are dispatched by
MessageType code, and modules are gated by JDK profiles. None of these links
show up in a static call graph, so this script extracts them from their
declarations and writes them as Markdown for AI coding assistants.

Usage:
    python3 tools/ai-docs/generate.py          # rewrite docs/ai/*.md
    python3 tools/ai-docs/generate.py --check  # fail if docs/ai/ is stale

Only the Python 3 standard library is used. Output is deterministic: no
timestamps and no line numbers, so it only changes when the wiring changes.
"""

import argparse
import difflib
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT_DIR = os.path.join(ROOT, "docs", "ai")

LICENSE_HEADER = """<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
"""

GENERATED_NOTE = (
    "> Generated by `tools/ai-docs/generate.py`. Do not edit by hand; "
    "run `make ai-docs` after changing the code it describes.\n"
)


# --------------------------------------------------------------------------
# Source index
# --------------------------------------------------------------------------


def git_ls_files(*patterns):
    out = subprocess.check_output(["git", "ls-files", "--", *patterns], cwd=ROOT, text=True)
    return sorted(line for line in out.splitlines() if line)


def is_main(path):
    return "/src/test/" not in path and not path.startswith("test-suite/")


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8", errors="replace") as f:
        return f.read()


def strip_comments(src):
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    return re.sub(r"//[^\n]*", "", src)


class JavaIndex:
    """Maps class names to source files for main (non-test) Java code."""

    def __init__(self):
        self.files = [p for p in git_ls_files("*.java") if is_main(p)]
        self.by_fqn = {}
        self.by_simple = defaultdict(list)
        self._src = {}
        for path in self.files:
            name = os.path.basename(path)[:-5]
            m = re.search(r"^\s*package\s+([\w.]+)\s*;", self.source(path), re.M)
            fqn = "%s.%s" % (m.group(1), name) if m else name
            self.by_fqn[fqn] = path
            self.by_simple[name].append(path)

    def source(self, path):
        if path not in self._src:
            self._src[path] = strip_comments(read(path))
        return self._src[path]

    def package_of(self, path):
        m = re.search(r"^\s*package\s+([\w.]+)\s*;", self.source(path), re.M)
        return m.group(1) if m else ""

    def resolve(self, simple, context_path):
        """Resolve a simple class name as seen from context_path to an FQN."""
        src = self.source(context_path)
        m = re.search(r"^\s*import\s+([\w.]+\.%s)\s*;" % re.escape(simple), src, re.M)
        if m:
            return m.group(1)
        same_pkg = "%s.%s" % (self.package_of(context_path), simple)
        if same_pkg in self.by_fqn:
            return same_pkg
        candidates = self.by_simple.get(simple, [])
        if len(candidates) == 1:
            return self.fqn_of(candidates[0])
        return None

    def superclasses(self, path):
        """Simple names of the classes `path` extends, nearest first."""
        chain = []
        current = path
        while current and len(chain) < 10:
            name = os.path.basename(current)[:-5]
            m = re.search(r"\bclass\s+%s\b[^{]*?\bextends\s+(\w+)" % re.escape(name), self.source(current))
            if not m:
                break
            chain.append(m.group(1))
            fqn = self.resolve(m.group(1), current)
            current = self.by_fqn.get(fqn) if fqn else None
        return chain

    def fqn_of(self, path):
        pkg = self.package_of(path)
        name = os.path.basename(path)[:-5]
        return "%s.%s" % (pkg, name) if pkg else name

    def resolve_constant(self, expr, context_path):
        """Turn `"db"` or `JdbcConstants.MYSQL` into its string value when possible."""
        expr = expr.strip()
        m = re.fullmatch(r'"([^"]*)"', expr)
        if m:
            return m.group(1)
        m = re.fullmatch(r"(\w+)\.(\w+)", expr)
        if m:
            fqn = self.resolve(m.group(1), context_path)
            path = self.by_fqn.get(fqn) if fqn else None
            if path:
                c = re.search(r'\b%s\s*=\s*"([^"]*)"' % re.escape(m.group(2)), self.source(path))
                if c:
                    return c.group(1)
        return None


def method_body(src, start):
    """Text from just after an opening brace at `start - 1` to its matching close brace."""
    depth = 1
    i = start
    while i < len(src) and depth:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
        i += 1
    return src[start:i]


def module_of(path):
    """Nearest directory above `path` that has a pom.xml."""
    d = os.path.dirname(path)
    while d:
        if os.path.exists(os.path.join(ROOT, d, "pom.xml")):
            return d
        d = os.path.dirname(d)
    return "."


def code(text):
    return "`%s`" % text


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |")
    return "\n".join(lines)


def document(title, intro, body):
    return "%s\n# %s\n\n%s\n%s\n\n%s\n" % (LICENSE_HEADER, title, GENERATED_NOTE, intro.strip(), body.strip())


# --------------------------------------------------------------------------
# SPI map
# --------------------------------------------------------------------------

LOAD_LEVEL_RE = re.compile(r"@LoadLevel\s*\((.*?)\)\s*(?:@\w+(?:\([^)]*\))?\s*)*(?:public\s+)?(?:abstract\s+|final\s+)*class\s+(\w+)", re.S)
LOAD_CALL_RE = re.compile(r"EnhancedServiceLoader\s*\.\s*(load|loadAll)\s*\(\s*([A-Z]\w*)\.class")


def parse_load_level(index, impl_fqn):
    path = index.by_fqn.get(impl_fqn)
    if not path:
        return None, "", ""
    simple = impl_fqn.rsplit(".", 1)[-1]
    for m in LOAD_LEVEL_RE.finditer(index.source(path)):
        if m.group(2) != simple:
            continue
        args = m.group(1)
        name_expr = re.search(r"name\s*=\s*([^,)]+)", args)
        if not name_expr:
            name_expr = re.match(r"\s*([^,=]+?)\s*(,|$)", args)
        name = ""
        if name_expr:
            raw = name_expr.group(1).strip()
            value = index.resolve_constant(raw, path)
            name = value if value is not None else raw
        order = re.search(r"order\s*=\s*(-?\w+)", args)
        scope = re.search(r"scope\s*=\s*(?:Scope\.)?(\w+)", args)
        extra = [order.group(1) if order else "", scope.group(1).lower() if scope else ""]
        return path, name, " / ".join(e for e in extra if e)
    return path, "", ""


def build_spi(index):
    services = [p for p in git_ls_files("*/META-INF/services/*", "*/META-INF/seata/*") if is_main(p)]
    impls_by_iface = defaultdict(list)
    for spi_file in services:
        iface = os.path.basename(spi_file)
        for line in read(spi_file).splitlines():
            impl = line.split("#", 1)[0].strip()
            if impl:
                impls_by_iface[iface].append((impl, spi_file))

    loaders = defaultdict(set)
    for path in index.files:
        for m in LOAD_CALL_RE.finditer(index.source(path)):
            fqn = index.resolve(m.group(2), path)
            if fqn:
                loaders[fqn].add(path)

    sections = []
    summary = []
    foreign = []
    for iface in sorted(impls_by_iface):
        if not iface.startswith(("org.apache.seata.", "io.seata.")):
            for impl, spi_file in sorted(set(impls_by_iface[iface])):
                foreign.append((code(iface), code(impl.rsplit(".", 1)[-1]), code(module_of(spi_file))))
            continue
        iface_path = index.by_fqn.get(iface)
        rows = []
        for impl, spi_file in sorted(set(impls_by_iface[iface])):
            impl_path, name, extra = parse_load_level(index, impl)
            rows.append((name, impl, impl_path or spi_file, extra))
        rows.sort(key=lambda r: (r[0] == "", r[0].lower(), r[1]))
        summary.append((iface, len(rows), module_of(iface_path) if iface_path else "?"))

        lines = ["## %s" % code(iface)]
        if iface_path:
            lines.append("Defined in %s." % code(iface_path))
        lines.append("")
        lines.append(table(
            ["Name", "Implementation", "Source", "Order / scope"],
            [(code(n) if n else "no `@LoadLevel`", code(i.rsplit(".", 1)[-1]), code(p), e or "-") for n, i, p, e in rows],
        ))
        if loaders.get(iface):
            lines.append("")
            lines.append("Loaded in: " + ", ".join(code(p) for p in sorted(loaders[iface])))
        sections.append("\n".join(lines))

    intro = """
Every SPI interface registered under `META-INF/services/`, its implementations,
and where `EnhancedServiceLoader` loads it. An implementation is selected at
runtime by the `Name` from its `@LoadLevel` annotation (for example a store mode
such as `db`, or a database type such as `mysql`); a higher `Order` wins when no
name is given. Constant names are resolved to their string values where possible.

Load sites only list calls of the form `EnhancedServiceLoader.load(X.class, ...)`.
Which configuration key decides the name is code flow, not a declaration, so it
is not listed here.
"""
    index_table = table(
        ["Interface", "Implementations", "Module"],
        [(code(i), str(n), code(m)) for i, n, m in summary],
    )
    body = "## Index\n\n" + index_table + "\n\n" + "\n\n".join(sections)
    if foreign:
        body += "\n\n## Extensions of other frameworks\n\nRegistered for the host RPC framework's own " \
                "service loader, not for `EnhancedServiceLoader`.\n\n"
        body += table(["Framework interface", "Implementation", "Module"], foreign)
    return document("SPI map", intro, body)


# --------------------------------------------------------------------------
# RPC map
# --------------------------------------------------------------------------

REGISTER_RE = re.compile(r"registerProcessor\s*\(\s*MessageType\.(\w+)\s*,\s*(\w+)\s*,\s*([\w.()]+)\s*\)")
NEW_VAR_RE = r"\b%s\s*=\s*new\s+(\w+)\s*[(<]"
HANDLE_RE = re.compile(r"public\s+[\w<>]+\s+handle\s*\(\s*(\w+)\s+\w+[^)]*\)\s*\{")


def build_rpc(index):
    mt_path = index.by_fqn["org.apache.seata.core.protocol.MessageType"]
    codes = dict(re.findall(r"\bshort\s+(TYPE_\w+)\s*=\s*(-?\d+)\s*;", index.source(mt_path)))

    messages = defaultdict(list)
    for path in index.files:
        for m in re.finditer(r"return\s+MessageType\.(TYPE_\w+)\s*;", index.source(path)):
            messages[m.group(1)].append(path)

    registrations = defaultdict(list)
    for path in index.files:
        src = index.source(path)
        for m in REGISTER_RE.finditer(src):
            var_type = re.search(NEW_VAR_RE % re.escape(m.group(2)), src)
            processor = var_type.group(1) if var_type else m.group(2)
            executor = "IO thread" if m.group(3) == "null" else m.group(3)
            registrations[m.group(1)].append((os.path.basename(path)[:-5], processor, executor, path))

    rows = []
    for name, value in sorted(codes.items(), key=lambda kv: (int(kv[1]), kv[0])):
        msg = ", ".join(code(os.path.basename(p)[:-5]) for p in sorted(messages.get(name, [])) if "/io/seata/" not in p)
        regs = "<br>".join(
            "%s → %s" % (owner, code(proc)) for owner, proc, _, _ in sorted(registrations.get(name, []))
        )
        rows.append((value, code(name), msg or "-", regs or "-"))
    message_table = table(["Code", "MessageType", "Message class", "Received by (remoting → processor)"], rows)

    owners = defaultdict(list)
    for name, regs in registrations.items():
        for owner, proc, executor, path in regs:
            owners[(owner, path)].append((name, proc, executor))
    owner_sections = []
    for (owner, path), regs in sorted(owners.items()):
        owner_sections.append("### %s\n\nRegistered in %s.\n\n%s" % (
            code(owner), code(path),
            table(["MessageType", "Processor", "Executor"],
                  [(code(n), code(p), e) for n, p, e in sorted(regs, key=lambda r: int(codes.get(r[0], 0)))]),
        ))

    dispatch_rows = []
    for path in index.files:
        src = index.source(path)
        handler = os.path.basename(path)[:-5]
        for m in HANDLE_RE.finditer(src):
            do_call = re.search(r"\b(do[A-Z]\w*)\s*\(", method_body(src, m.end()))
            if not do_call or not m.group(1).endswith("Request"):
                continue
            impls = sorted(
                os.path.basename(p)[:-5]
                for p in index.files
                if p != path
                and handler in index.superclasses(p)
                and re.search(r"(protected|public)\s+void\s+%s\s*\(" % do_call.group(1), index.source(p))
            )
            dispatch_rows.append((
                code(m.group(1)),
                code("%s#handle" % handler),
                code(do_call.group(1)),
                ", ".join(code(c) for c in impls) or "%s (no override)" % code(handler),
            ))
    dispatch_rows.sort()

    others = []
    for path in index.files:
        for m in re.finditer(r"\w+\.registerProcessor\s*\(\s*new\s+(\w+)\s*\(", index.source(path)):
            others.append((code(m.group(1)), code(path)))

    intro = """
How a Seata RPC message travels. Netty remoting classes register one processor
per `MessageType` code in a dispatch table (`AbstractNettyRemoting#processorTable`),
so a processor is never called directly and has no callers in a static call graph.
`IO thread` means the processor runs on the Netty I/O thread (no executor).
"""
    body = "## Message types\n\n" + message_table
    body += "\n\n## Processors by remoting endpoint\n\n" + "\n\n".join(owner_sections)
    body += "\n\n## Request handling\n\nTransaction requests reach their handler through `request.handle(handler)`, " \
            "which picks the `handle` overload by request type and then calls a `do*` method.\n\n"
    body += table(["Request", "Entry point", "Calls", "Implemented in"], dispatch_rows)
    if others:
        body += "\n\n## Other processors\n\nRegistered on non-Netty RPC servers (for example the Raft RPC server).\n\n"
        body += table(["Processor", "Registered in"], sorted(set(others)))
    return document("RPC map", intro, body)


# --------------------------------------------------------------------------
# Module map
# --------------------------------------------------------------------------


def strip_ns(elem):
    for e in elem.iter():
        if isinstance(e.tag, str) and "}" in e.tag:
            e.tag = e.tag.split("}", 1)[1]
    return elem


def text(elem, tag):
    child = elem.find(tag)
    return child.text.strip() if child is not None and child.text else ""


def build_modules():
    poms = {}
    for pom in git_ls_files("pom.xml", "*/pom.xml"):
        try:
            root = strip_ns(ET.parse(os.path.join(ROOT, pom)).getroot())
        except ET.ParseError:
            continue
        poms[os.path.dirname(pom) or "."] = root

    artifact_of = {d: text(r, "artifactId") for d, r in poms.items()}
    known = set(artifact_of.values())

    root_pom = poms["."]
    default_modules = [m.text.strip() for m in root_pom.findall("modules/module")]
    gated = []
    for profile in root_pom.findall("profiles/profile"):
        jdk = text(profile, "activation/jdk")
        mods = [m.text.strip() for m in profile.findall("modules/module")]
        if jdk and mods:
            gated.append((jdk, text(profile, "id"), mods))

    rows = []
    for d in sorted(poms):
        if d == ".":
            continue
        r = poms[d]
        deps = []
        for dep in r.findall("dependencies/dependency"):
            aid = text(dep, "artifactId")
            if aid in known and aid != artifact_of[d]:
                scope = text(dep, "scope")
                deps.append(aid + (" (%s)" % scope if scope and scope != "compile" else ""))
        rows.append((code(d), code(artifact_of[d]), text(r, "packaging") or "jar", ", ".join(sorted(deps)) or "-"))

    gate_rows = [(code(jdk), code(pid), ", ".join(code(m) for m in mods)) for jdk, pid, mods in gated]
    intro = """
Maven modules of this repository and how they depend on each other. Use the
directory with `./mvnw -pl <dir> -am` to build one module with its dependencies.
Some modules are only part of the reactor on newer JDKs, so a build on an older
JDK silently skips them.
"""
    body = "## JDK-gated modules\n\nDeclared as JDK-activated profiles in the root `pom.xml`. " \
           "The default build lists %d modules.\n\n" % len(default_modules)
    body += table(["Activated on JDK", "Profile", "Adds modules"], gate_rows)
    body += "\n\n## Modules\n\nOnly dependencies on other modules of this repository are listed.\n\n"
    body += table(["Directory", "ArtifactId", "Packaging", "Depends on"], rows)
    return document("Module map", intro, body)


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

README_BODY = """
Reference material for AI coding assistants working on this repository.
Static analysis misses most of Seata's wiring: implementations are chosen at
runtime by name, RPC messages are dispatched by code, and modules are gated by
JDK version. These maps list those links so an assistant can look them up
instead of rediscovering them.

| File | Answers |
|---|---|
| [spi.md](spi.md) | Which implementations exist for an SPI interface, under which name, and where it is loaded |
| [rpc.md](rpc.md) | Which class a message type maps to, which processor receives it, and which method handles it |
| [modules.md](modules.md) | Which directory builds which artifact, what it depends on, and which JDK it needs |

The maps are generated from the code. If one looks wrong, fix the generator in
`tools/ai-docs/generate.py`, not the Markdown. CI runs `make ai-docs-check` and
fails when the maps are out of date; run `make ai-docs` to refresh them.
"""


def render_all():
    index = JavaIndex()
    return {
        "README.md": "%s\n# AI reference maps\n\n%s\n%s" % (LICENSE_HEADER, GENERATED_NOTE, README_BODY.lstrip()),
        "spi.md": build_spi(index),
        "rpc.md": build_rpc(index),
        "modules.md": build_modules(),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="fail if docs/ai/ is out of date")
    args = parser.parse_args()

    rendered = render_all()
    if args.check:
        stale = []
        for name, content in sorted(rendered.items()):
            path = os.path.join(OUT_DIR, name)
            current = read(path) if os.path.exists(path) else ""
            if current != content:
                stale.append(name)
                diff = difflib.unified_diff(
                    current.splitlines(), content.splitlines(), "docs/ai/" + name, "generated", lineterm="", n=1)
                print("\n".join(list(diff)[:40]))
        if stale:
            print("\ndocs/ai/ is out of date: %s\nRun `make ai-docs` and commit the result." % ", ".join(stale))
            return 1
        print("docs/ai/ is up to date.")
        return 0

    os.makedirs(OUT_DIR, exist_ok=True)
    for name, content in rendered.items():
        with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as f:
            f.write(content)
    print("Wrote %d files to docs/ai/." % len(rendered))
    return 0


if __name__ == "__main__":
    sys.exit(main())
